### ISSUE TITLE
'charmap' codec can't decode byte 0x98

### ISSUE THREAD

**Issue by kokochka** [SuperZombi/MyTube-GUI#2]
![image](https://github.com/user-attachments/assets/b2ef7274-8db1-410d-9578-cf21a09a781e)

```
'charmap' codec can't decode byte 0x98 in position 61: character maps to <undefined>
```

**Comment by SuperZombi** [comment]
Fixed in [`0.7.3`](https://github.com/SuperZombi/MyTube-GUI/releases/tag/0.7.3)
